name: DollBuilder
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: JR <email@example.com>
environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: ^0.6.0
  xml: "^2.6.0"
  source_map_stack_trace: ^1.1.4
  archive: "^1.0.31"
  DollLibCorrect:
    git: git://github.com/jadedResearcher/DollLibCorrect.git
  RenderingLib:
    git: git://github.com/jadedResearcher/RenderingLib.git
  LoaderLib:
      git: git://github.com/FarragoFiction/LoaderLib.git
  TextEngine:
      git: git://github.com/FarragoFiction/TextEngine.git

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- $dart2js:
    sourceMaps: true
    commandLineOptions: [--fast-startup, --trust-type-annotations]
    $exclude: ["web/manifest/tarbuilder.dart", "web/manifest/sourcemanifest.txt"]